### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by UqygaDev** [KittenCN/predict_Lottery_ticket#3]
Traceback (most recent call last):
  File "E:\predict_Lottery_ticket-main\run_predict.py", line 52, in <module>
    _data, _title = predict_run(args.name)
  File "E:\predict_Lottery_ticket-main\common.py", line 422, in predict_run
    predict_features_ = try_error(name, data, windows_size)
  File "E:\predict_Lottery_ticket-main\common.py", line 320, in try_error
    if len(predict_features) != windows_size:
TypeError: object of type 'NoneType' has no len()Traceback (most recent call last):
  File "E:\predict_Lottery_ticket-main\run_predict.py", line 52, in <module>
    _data, _title = predict_run(args.name)
  File "E:\predict_Lottery_ticket-main\common.py", line 422, in predict_run
    predict_features_ = try_error(name, data, windows_size)
  File "E:\predict_Lottery_ticket-main\common.py", line 320, in try_error
    if len(predict_features) != windows_size:
TypeError: object of type 'NoneType' has no len()

**Comment by KittenCN** [comment]
你有正常的获取当前数据和训练模型吗？

**Comment by shaneluik1026** [comment]
同样的报错，获取数据了也训练了模型。但是预测的时候就报这个错误，用的是GPU训练和预测的。

**Comment by KittenCN** [comment]
训练的参数发来看看

**Comment by KittenCN** [comment]
检查一下训练与预测的参数是否一致，我原始的参数，cq值不一致，会导致错误，已经更新了
