### ISSUE TITLE
RuntimeError: permute(sparse_coo): 

### ISSUE THREAD

**Issue by GreekPanda** [KittenCN/predict_Lottery_ticket#9]
大佬，运行不起来。错误日志：
D:\study\ml\predict_Lottery_ticket_pytorch-master>python run_train_model.py --name ssq  --windows_size 3,5,7 --red_epochs 1 --blue_epochs 1 --batch_size 1
2023-05-17 10:40:51.928 | INFO     | __main__:<module>:135 - 正在创建【双色球】数据集...
2023-05-17 10:40:51.929 | INFO     | __main__:action:95 - 正在创建【双色球】数据集...
2023-05-17 10:40:51.936 | INFO     | common:create_train_data:41 - 训练数据已加载!
2023-05-17 10:40:51.952 | INFO     | common:create_train_data:72 - 训练集数据维度: (2996, 4, 6, 1)
2023-05-17 10:40:51.955 | INFO     | common:create_train_data:41 - 训练数据已加载!
2023-05-17 10:40:52.012 | INFO     | common:create_train_data:72 - 训练集数据维度: (2996, 4, 6, 1)
2023-05-17 10:40:52.017 | INFO     | __main__:action:100 - 开始训练【双色球】红球模型...
2023-05-17 10:40:52.021 | INFO     | __main__:train_ball_model:57 - 标签数据维度: (2996, 4, 6, 1)
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "D:\study\ml\predict_Lottery_ticket_pytorch-master\run_train_model.py", line 177, in <module>
    run(args.name, list_windows_size)
  File "D:\study\ml\predict_Lottery_ticket_pytorch-master\run_train_model.py", line 124, in run
    action(name)
  File "D:\study\ml\predict_Lottery_ticket_pytorch-master\run_train_model.py", line 102, in action
    train_ball_model(name, dataset=red_data, sub_name="红球")
  File "D:\study\ml\predict_Lottery_ticket_pytorch-master\run_train_model.py", line 77, in train_ball_model
    y_pred = model(x.float())
  File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\study\ml\predict_Lottery_ticket_pytorch-master\modeling.py", line 125, in forward
    x = x.permute(1, 0, 2) # 将输入序列转置为 (seq_len, batch_size, input_size)
RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]

**Comment by KittenCN** [comment]
你有修改什么东西吗？特征维度不对啊。我这里维度是3， 你的报错说是维度4了, 我测试了最新的代码，最新的数据，按照你的参数 --name ssq --windows_size 3,5,7 --red_epochs 1 --blue_epochs 1 --batch_size 1，其他均默认的情况下，是能正常运行的

**Comment by GreekPanda** [comment]
没有修改任何东西，就是直接运行你的代码，然后就报错，现在还是同样的错误，莫非是版本的原因?
Python 3.8.10
>>> import torch
>>> torch.__version__
'2.0.1'

**Comment by KittenCN** [comment]
我这里不能复现这个错误，在我提供的版本下
